version: '3.7'
services:
  mongodb:
    image: mongo
    environment:
      env_file: ./infra/envs/mongodb.env
    ports:
      - 27017:27017

  api:
    build: ./api
    command: npm run start
    env_file: ./infra/envs/api.env
    ports:
      - 3002:3002
    depends_on: 
      - mongodb
    healthcheck:
      test: curl --fail -s http://0.0.0.0:3002/ || exit 1
      interval: 20s
      timeout: 5s
      retries: 3

  client:
    build: ./client
    command: yarn start
    env_file: ./infra/envs/client.env
    ports:
      - 3000:3000
    depends_on:
      - api
    healthcheck:
      test: curl --fail -s http://0.0.0.0:3000/ || exit 1
      interval: 20s
      timeout: 5s
      retries: 3